name: Update README with my Gists

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repoistory
        uses: actions/checkout@v2
        
      - name: Fetch Gists
        id: fetch-gists
        run: |
          curl -s "https://api.github.com/users/laurenashley/gists" > gists.json

      - name: Update README
        run: |
          python update_readme.py
      
      - name: Commit changes
        uses: laurenashley/git-auto-commit-action@v4
        with: 
          commit_message: "Update README with my latest gists"
          branch: main